import ExcelJS from 'exceljs'; import fs from 'fs';
const wb=new ExcelJS.Workbook(); await wb.xlsx.load(fs.readFileSync('/tmp/base.xlsx'));
const ws=wb.getWorksheet('BASE');
ws.duplicateRow(20,4,true);
console.log('B23',ws.getCell('B23').value,'B27',ws.getCell('B27').value,'M37',ws.getCell('M37').value,'M41',ws.getCell('M41').value);
const buf=Buffer.from(await wb.xlsx.writeBuffer()); fs.writeFileSync('/tmp/dup.xlsx',buf);
const wb2=new ExcelJS.Workbook(); await wb2.xlsx.load(buf);
const s=wb2.getWorksheet('BASE');
console.log('after reload B27',s.getCell('B27').value, 'F27', s.getCell('F27').value);
console.log('merges', Object.keys(s._merges||{}).slice(0,80));
