/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSeguimientosRouteImport } from './routes/_authenticated/seguimientos'
import { Route as AuthenticatedRemisionesRouteImport } from './routes/_authenticated/remisiones'
import { Route as AuthenticatedReglasRouteImport } from './routes/_authenticated/reglas'
import { Route as AuthenticatedRedIpsRouteImport } from './routes/_authenticated/red-ips'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedControlMandoRouteImport } from './routes/_authenticated/control-mando'
import { Route as AuthenticatedCatalogoRouteImport } from './routes/_authenticated/catalogo'
import { Route as AuthenticatedCasosRouteImport } from './routes/_authenticated/casos'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSeguimientosRoute =
  AuthenticatedSeguimientosRouteImport.update({
    id: '/seguimientos',
    path: '/seguimientos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRemisionesRoute = AuthenticatedRemisionesRouteImport.update({
  id: '/remisiones',
  path: '/remisiones',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReglasRoute = AuthenticatedReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRedIpsRoute = AuthenticatedRedIpsRouteImport.update({
  id: '/red-ips',
  path: '/red-ips',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedControlMandoRoute =
  AuthenticatedControlMandoRouteImport.update({
    id: '/control-mando',
    path: '/control-mando',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogoRoute = AuthenticatedCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCasosRoute = AuthenticatedCasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/casos': typeof AuthenticatedCasosRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/control-mando': typeof AuthenticatedControlMandoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/red-ips': typeof AuthenticatedRedIpsRoute
  '/reglas': typeof AuthenticatedReglasRoute
  '/remisiones': typeof AuthenticatedRemisionesRoute
  '/seguimientos': typeof AuthenticatedSeguimientosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/casos': typeof AuthenticatedCasosRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/control-mando': typeof AuthenticatedControlMandoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/red-ips': typeof AuthenticatedRedIpsRoute
  '/reglas': typeof AuthenticatedReglasRoute
  '/remisiones': typeof AuthenticatedRemisionesRoute
  '/seguimientos': typeof AuthenticatedSeguimientosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/casos': typeof AuthenticatedCasosRoute
  '/_authenticated/catalogo': typeof AuthenticatedCatalogoRoute
  '/_authenticated/control-mando': typeof AuthenticatedControlMandoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/red-ips': typeof AuthenticatedRedIpsRoute
  '/_authenticated/reglas': typeof AuthenticatedReglasRoute
  '/_authenticated/remisiones': typeof AuthenticatedRemisionesRoute
  '/_authenticated/seguimientos': typeof AuthenticatedSeguimientosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacidad'
    | '/sitemap.xml'
    | '/casos'
    | '/catalogo'
    | '/control-mando'
    | '/dashboard'
    | '/historial'
    | '/indicadores'
    | '/red-ips'
    | '/reglas'
    | '/remisiones'
    | '/seguimientos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacidad'
    | '/sitemap.xml'
    | '/casos'
    | '/catalogo'
    | '/control-mando'
    | '/dashboard'
    | '/historial'
    | '/indicadores'
    | '/red-ips'
    | '/reglas'
    | '/remisiones'
    | '/seguimientos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacidad'
    | '/sitemap.xml'
    | '/_authenticated/casos'
    | '/_authenticated/catalogo'
    | '/_authenticated/control-mando'
    | '/_authenticated/dashboard'
    | '/_authenticated/historial'
    | '/_authenticated/indicadores'
    | '/_authenticated/red-ips'
    | '/_authenticated/reglas'
    | '/_authenticated/remisiones'
    | '/_authenticated/seguimientos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacidadRoute: typeof PrivacidadRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seguimientos': {
      id: '/_authenticated/seguimientos'
      path: '/seguimientos'
      fullPath: '/seguimientos'
      preLoaderRoute: typeof AuthenticatedSeguimientosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/remisiones': {
      id: '/_authenticated/remisiones'
      path: '/remisiones'
      fullPath: '/remisiones'
      preLoaderRoute: typeof AuthenticatedRemisionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reglas': {
      id: '/_authenticated/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof AuthenticatedReglasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/red-ips': {
      id: '/_authenticated/red-ips'
      path: '/red-ips'
      fullPath: '/red-ips'
      preLoaderRoute: typeof AuthenticatedRedIpsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/control-mando': {
      id: '/_authenticated/control-mando'
      path: '/control-mando'
      fullPath: '/control-mando'
      preLoaderRoute: typeof AuthenticatedControlMandoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogo': {
      id: '/_authenticated/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AuthenticatedCatalogoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/casos': {
      id: '/_authenticated/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof AuthenticatedCasosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCasosRoute: typeof AuthenticatedCasosRoute
  AuthenticatedCatalogoRoute: typeof AuthenticatedCatalogoRoute
  AuthenticatedControlMandoRoute: typeof AuthenticatedControlMandoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedRedIpsRoute: typeof AuthenticatedRedIpsRoute
  AuthenticatedReglasRoute: typeof AuthenticatedReglasRoute
  AuthenticatedRemisionesRoute: typeof AuthenticatedRemisionesRoute
  AuthenticatedSeguimientosRoute: typeof AuthenticatedSeguimientosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCasosRoute: AuthenticatedCasosRoute,
  AuthenticatedCatalogoRoute: AuthenticatedCatalogoRoute,
  AuthenticatedControlMandoRoute: AuthenticatedControlMandoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedRedIpsRoute: AuthenticatedRedIpsRoute,
  AuthenticatedReglasRoute: AuthenticatedReglasRoute,
  AuthenticatedRemisionesRoute: AuthenticatedRemisionesRoute,
  AuthenticatedSeguimientosRoute: AuthenticatedSeguimientosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacidadRoute: PrivacidadRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
